import Head from "next/head";
import { Inter } from "@next/font/google";

import styles from "@/styles/Home.module.css";
import {
  Box,
  Button,
  Center,
  Grid,
  GridItem,
  Heading,
  Image,
  Text,
  Flex
} from "@chakra-ui/react";
import Home from "./Home";

const inter = Inter({ subsets: ["latin"] });

export default function Homee() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <main>
        <Box bg="#050017" color={"white"}>

{/* main image */}
          <Image 
        position="absolute"
          w={["65%","65%", "65%","65%","65%"]}
              right={[ "-1px","1px","1px","1px","1px"]}
              top={["0px","0px","0px","0px","-1px"]}
              zIndex= "1"
            src="/utils/Common/banner-img.png"
            alt="pborbit"
          />

          {/* orage */}
          <Image
            position="absolute"
           left={["118px","258px","270px","505px","471px"]}
            top={["0px","0px","0px","0px","0px"]}
             w={["88%","85%","85%","85%","85%"]}
            
            src="/utils/Common/ns2.png"
            alt="pborbit"
          />
          <Image
           
            zIndex= "1"
            position="absolute"
            left={["-70px","-75px","75px","-73px","-172px"]}
            top={["85px","80px","80px","252px","252px"]}
             w={["27%","16%","16%","16%","16%"]}
            src="/utils/Common/bsi1.png"
            alt="pborbit"
          />
          <Image
            // style={{ position: "absolute", left: "-140px", top: "480px" }}
            position="absolute"
            left={["-75px","258px","270px","-73px","-172px"]}
            top={["84px","0px","0px","252px","252"]}
             w={["29%","16%","16%","16%","16%"]}
            src="/utils/Common/bsi2.png"
            alt="pborbit"
          />

          <Image
            style={{ position: "absolute", left: "-140px", bottom: "800px" }}
            src="/utils/Common/dot-bg.png"
            alt="pborbit"
          />
          <Image
            style={{
              position: "absolute",
              right: "-20px",
              // left: "1140px",
              top: "940px",
              zIndex: 1,
            }}
            src="/utils/Common/half-circle.png"
            alt="pborbit"
          />
{/* leading page */}
          <Home />
        </Box>
      </main>
    </>
  );
}
