import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import {
  Box,
 
} from "@chakra-ui/react";
const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <Box>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main >
      <Box>
<img style={{position:"relative"}} src="https://www.freecodecamp.org/news/content/images/size/w2000/2021/06/w-qjCHPZbeXCQ-unsplash.jpg" />
<p>yetreurteuyrte
  gfufgwefgew

  kgdaskjgkajsssssh
  ss
  s
  s
  s
  s
  s
  s
  s
  s
  s
</p>

      </Box>
    
      </main>
    </Box>
  )
}
